### ISSUE TITLE
RSA key format is not supported

### ISSUE THREAD

**Issue by lintran-cn** [guanjiangtao/ibox_crypto#3]
Traceback (most recent call last):
  File "crypto.py", line 21, in <module>
    result = decrypt(args[2], args[3])
  File "/Users/Documents/FlutterProject/ibox/ibox_crypto-master/tools.py", line 65, in decrypt
    rsa = __decode_rsa(data=encryptKey, private_key=private_key)
  File "/Users/Documents/FlutterProject/ibox/ibox_crypto-master/tools.py", line 35, in __decode_rsa
    rsa_key = RSA.importKey(key.encode('utf-8'))
  File "/Users/Library/Python/3.8/lib/python/site-packages/Cryptodome/PublicKey/RSA.py", line 770, in import_key
    return _import_keyDER(der, passphrase)
  File "/Users/Library/Python/3.8/lib/python/site-packages/Cryptodome/PublicKey/RSA.py", line 685, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported

**Comment by lintran-cn** [comment]
https://www.ibox.art/zh-cn/item/group/?id=100513860 
i use this request response
